Repository ManageIQ/optimist, pull requests merged in 2024-05, with the labels that each got.

#150 adding support for DidYouMean when long options are spelled incorrectly
  examples/didyoumean.rb
  lib/optimist.rb
  test/optimist/parser_test.rb
Labels: enhancement

#149 Enable frozen_string_literal for future-ruby support
  lib/optimist.rb
Labels: enhancement

#147 Using permitted: restricts the allowed values that a end-user inputs to a pre-defined list
  lib/optimist.rb
  test/optimist/parser_educate_test.rb
  test/optimist/parser_test.rb
Labels: enhancement

#152 Allow failures for ruby-head
  .github/workflows/ci.yaml
Labels: test

#155 added settings to only create short options explicitly
  lib/optimist.rb
  test/optimist/parser_test.rb
Labels: enhancement

#151 Add alt longname and multiple char support
  examples/alt_names.rb
  lib/optimist.rb
  test/optimist/alt_names_test.rb
  test/optimist/parser_test.rb
Labels: enhancement

#156 Refactor constraints
  examples/constraints.rb
  lib/optimist.rb
  test/optimist/parser_constraint_test.rb
  test/optimist/parser_test.rb
Labels: refactoring

#160 Fix assert_raises to assert_raises_errmatch
  lib/optimist.rb
  test/optimist/alt_names_test.rb
  test/optimist/parser_constraint_test.rb
  test/optimist/parser_parse_test.rb
  test/optimist/parser_permitted_test.rb
  test/optimist/parser_test.rb
  test/optimist_test.rb
Labels: test
